package com.trustmesh.app.core.intelligence.risk

enum class RiskFactorType {
    UNKNOWN_CALLER,
    KNOWN_CONTACT,
    IDENTITY_UNRESOLVED,
    IDENTITY_CONFIRMED,
    SUSPICIOUS_NOTIFICATION,
    FINANCIAL_NOTIFICATION,
    SECURITY_NOTIFICATION,
    MULTIPLE_RELATED_EVENTS,
    RAPID_EVENT_SEQUENCE,
    REPEATED_CALL,
    RECENT_UNKNOWN_INTERACTION,
    EXTERNAL_HIGH_RISK_REPUTATION,
    EXTERNAL_FRAUD_REPORT,
    EXTERNAL_SPAM_REPORT,
    KNOWN_BUSINESS_IDENTITY,
    EXTERNAL_IDENTITY_CONFIDENCE
}
