package com.trustmesh.app.core.intelligence.risk

enum class RiskFactorType {
    UNKNOWN_CALLER,
    KNOWN_CONTACT,
    IDENTITY_UNRESOLVED,
    IDENTITY_CONFIRMED,
    SUSPICIOUS_NOTIFICATION,
    FINANCIAL_NOTIFICATION,
    SECURITY_NOTIFICATION,
    MULTIPLE_RELATED_EVENTS,
    RAPID_EVENT_SEQUENCE,
    REPEATED_CALL,
    RECENT_UNKNOWN_INTERACTION,
    EXTERNAL_HIGH_RISK_REPUTATION,
    EXTERNAL_FRAUD_REPORT,
    EXTERNAL_SPAM_REPORT,
    KNOWN_BUSINESS_IDENTITY,
    EXTERNAL_IDENTITY_CONFIDENCE,
    
    // Extracted Intents
    INTENT_FINANCIAL,
    INTENT_OTP_VERIFICATION,
    INTENT_REMOTE_ACCESS,
    INTENT_URGENCY,
    INTENT_SOCIAL_ENGINEERING,
    INTENT_THREAT_OR_SUSPENSION,
    INTENT_MALICIOUS_LINK,
    CALLBACK_NUMBER,
    CALLBACK_NUMBER_MISMATCH,
    PACKAGE_ADDED,

    // Groq Semantic Intelligence Factors
    GROQ_SEMANTIC_SCAM_INTENT,
    GROQ_PSYCHOLOGICAL_URGENCY,
    GROQ_AUTHORITY_IMPERSONATION,
    GROQ_FINANCIAL_COERCION
}
